// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"
)

const countLeaderboardSnapshots = `-- name: CountLeaderboardSnapshots :one
SELECT count(*) FROM leaderboard_snapshots
`

func (q *Queries) CountLeaderboardSnapshots(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLeaderboardSnapshots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLeaderboardSnapshot = `-- name: GetLeaderboardSnapshot :one
SELECT id, scope, period, window_from, window_until, player_count, entries, created_at FROM leaderboard_snapshots
WHERE scope = $1
  AND period = $2
  AND window_from = $3
`

type GetLeaderboardSnapshotParams struct {
	Scope      string
	Period     string
	WindowFrom time.Time
}

func (q *Queries) GetLeaderboardSnapshot(ctx context.Context, arg GetLeaderboardSnapshotParams) (LeaderboardSnapshot, error) {
	row := q.db.QueryRow(ctx, getLeaderboardSnapshot, arg.Scope, arg.Period, arg.WindowFrom)
	var i LeaderboardSnapshot
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Period,
		&i.WindowFrom,
		&i.WindowUntil,
		&i.PlayerCount,
		&i.Entries,
		&i.CreatedAt,
	)
	return i, err
}

const topPlayersForGameAllTime = `-- name: TopPlayersForGameAllTime :many
SELECT user_id, max(points)::int AS points
FROM score_events
WHERE game = $1
GROUP BY user_id
ORDER BY points DESC, min(achieved_at)
LIMIT $2
`

type TopPlayersForGameAllTimeParams struct {
	Game  string
	Limit int32
}

type TopPlayersForGameAllTimeRow struct {
	UserID int64
	Points int32
}

func (q *Queries) TopPlayersForGameAllTime(ctx context.Context, arg TopPlayersForGameAllTimeParams) ([]TopPlayersForGameAllTimeRow, error) {
	rows, err := q.db.Query(ctx, topPlayersForGameAllTime, arg.Game, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopPlayersForGameAllTimeRow{}
	for rows.Next() {
		var i TopPlayersForGameAllTimeRow
		if err := rows.Scan(&i.UserID, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPlayersForGameInWindow = `-- name: TopPlayersForGameInWindow :many
SELECT user_id, max(points)::int AS points
FROM score_events
WHERE game = $1
  AND achieved_at >= $2
  AND achieved_at < $3
GROUP BY user_id
ORDER BY points DESC, min(achieved_at)
LIMIT $4
`

type TopPlayersForGameInWindowParams struct {
	Game         string
	AchievedAt   time.Time
	AchievedAt_2 time.Time
	Limit        int32
}

type TopPlayersForGameInWindowRow struct {
	UserID int64
	Points int32
}

func (q *Queries) TopPlayersForGameInWindow(ctx context.Context, arg TopPlayersForGameInWindowParams) ([]TopPlayersForGameInWindowRow, error) {
	rows, err := q.db.Query(ctx, topPlayersForGameInWindow,
		arg.Game,
		arg.AchievedAt,
		arg.AchievedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopPlayersForGameInWindowRow{}
	for rows.Next() {
		var i TopPlayersForGameInWindowRow
		if err := rows.Scan(&i.UserID, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPlayersGlobalAllTime = `-- name: TopPlayersGlobalAllTime :many
SELECT user_id, sum(best)::int AS points
FROM (
    SELECT user_id, game, max(points) AS best, min(achieved_at) AS first_at
    FROM score_events
    GROUP BY user_id, game
) per_game
GROUP BY user_id
ORDER BY points DESC, min(first_at)
LIMIT $1
`

type TopPlayersGlobalAllTimeRow struct {
	UserID int64
	Points int32
}

func (q *Queries) TopPlayersGlobalAllTime(ctx context.Context, limit int32) ([]TopPlayersGlobalAllTimeRow, error) {
	rows, err := q.db.Query(ctx, topPlayersGlobalAllTime, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopPlayersGlobalAllTimeRow{}
	for rows.Next() {
		var i TopPlayersGlobalAllTimeRow
		if err := rows.Scan(&i.UserID, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPlayersGlobalInWindow = `-- name: TopPlayersGlobalInWindow :many
SELECT user_id, sum(best)::int AS points
FROM (
    SELECT user_id, game, max(points) AS best, min(achieved_at) AS first_at
    FROM score_events
    WHERE achieved_at >= $1
      AND achieved_at < $2
    GROUP BY user_id, game
) per_game
GROUP BY user_id
ORDER BY points DESC, min(first_at)
LIMIT $3
`

type TopPlayersGlobalInWindowParams struct {
	AchievedAt   time.Time
	AchievedAt_2 time.Time
	Limit        int32
}

type TopPlayersGlobalInWindowRow struct {
	UserID int64
	Points int32
}

func (q *Queries) TopPlayersGlobalInWindow(ctx context.Context, arg TopPlayersGlobalInWindowParams) ([]TopPlayersGlobalInWindowRow, error) {
	rows, err := q.db.Query(ctx, topPlayersGlobalInWindow, arg.AchievedAt, arg.AchievedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopPlayersGlobalInWindowRow{}
	for rows.Next() {
		var i TopPlayersGlobalInWindowRow
		if err := rows.Scan(&i.UserID, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLeaderboardSnapshot = `-- name: UpsertLeaderboardSnapshot :one
INSERT INTO leaderboard_snapshots (scope, period, window_from, window_until, player_count, entries)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (scope, period, window_from) DO UPDATE
SET window_until = excluded.window_until,
    player_count = excluded.player_count,
    entries      = excluded.entries,
    created_at   = now()
RETURNING id, scope, period, window_from, window_until, player_count, entries, created_at
`

type UpsertLeaderboardSnapshotParams struct {
	Scope       string
	Period      string
	WindowFrom  time.Time
	WindowUntil time.Time
	PlayerCount int32
	Entries     []byte
}

func (q *Queries) UpsertLeaderboardSnapshot(ctx context.Context, arg UpsertLeaderboardSnapshotParams) (LeaderboardSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertLeaderboardSnapshot,
		arg.Scope,
		arg.Period,
		arg.WindowFrom,
		arg.WindowUntil,
		arg.PlayerCount,
		arg.Entries,
	)
	var i LeaderboardSnapshot
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Period,
		&i.WindowFrom,
		&i.WindowUntil,
		&i.PlayerCount,
		&i.Entries,
		&i.CreatedAt,
	)
	return i, err
}
