// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const abandonActiveSessions = `-- name: AbandonActiveSessions :execrows
UPDATE game_sessions
SET status      = 'abandoned',
    finished_at = now()
WHERE user_id = $1
  AND game = $2
  AND status = 'active'
`

type AbandonActiveSessionsParams struct {
	UserID int64
	Game   string
}

func (q *Queries) AbandonActiveSessions(ctx context.Context, arg AbandonActiveSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, abandonActiveSessions, arg.UserID, arg.Game)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveGameSessions = `-- name: CountActiveGameSessions :one
SELECT count(*) FROM game_sessions
WHERE user_id = $1
  AND status = 'active'
`

func (q *Queries) CountActiveGameSessions(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveGameSessions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGameSession = `-- name: CreateGameSession :one
INSERT INTO game_sessions (user_id, game, seed, state, deadline_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, game, seed, state, status, moves, started_at, deadline_at, finished_at
`

type CreateGameSessionParams struct {
	UserID     int64
	Game       string
	Seed       int64
	State      []byte
	DeadlineAt *time.Time
}

func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, createGameSession,
		arg.UserID,
		arg.Game,
		arg.Seed,
		arg.State,
		arg.DeadlineAt,
	)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Game,
		&i.Seed,
		&i.State,
		&i.Status,
		&i.Moves,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
	)
	return i, err
}

const createScoreEvent = `-- name: CreateScoreEvent :one
INSERT INTO score_events (user_id, session_id, game, raw, points)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, session_id, game, raw, points, achieved_at, projected_at
`

type CreateScoreEventParams struct {
	UserID    int64
	SessionID uuid.UUID
	Game      string
	Raw       float64
	Points    int32
}

func (q *Queries) CreateScoreEvent(ctx context.Context, arg CreateScoreEventParams) (ScoreEvent, error) {
	row := q.db.QueryRow(ctx, createScoreEvent,
		arg.UserID,
		arg.SessionID,
		arg.Game,
		arg.Raw,
		arg.Points,
	)
	var i ScoreEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Game,
		&i.Raw,
		&i.Points,
		&i.AchievedAt,
		&i.ProjectedAt,
	)
	return i, err
}

const finishGameSession = `-- name: FinishGameSession :one
UPDATE game_sessions
SET status      = 'finished',
    finished_at = now()
WHERE id = $1
  AND status = 'active'
RETURNING id, user_id, game, seed, state, status, moves, started_at, deadline_at, finished_at
`

func (q *Queries) FinishGameSession(ctx context.Context, id uuid.UUID) (GameSession, error) {
	row := q.db.QueryRow(ctx, finishGameSession, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Game,
		&i.Seed,
		&i.State,
		&i.Status,
		&i.Moves,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGameSession = `-- name: GetGameSession :one
SELECT id, user_id, game, seed, state, status, moves, started_at, deadline_at, finished_at FROM game_sessions
WHERE id = $1
`

func (q *Queries) GetGameSession(ctx context.Context, id uuid.UUID) (GameSession, error) {
	row := q.db.QueryRow(ctx, getGameSession, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Game,
		&i.Seed,
		&i.State,
		&i.Status,
		&i.Moves,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
	)
	return i, err
}

const getScoreEventBySession = `-- name: GetScoreEventBySession :one
SELECT id, user_id, session_id, game, raw, points, achieved_at, projected_at FROM score_events
WHERE session_id = $1
`

func (q *Queries) GetScoreEventBySession(ctx context.Context, sessionID uuid.UUID) (ScoreEvent, error) {
	row := q.db.QueryRow(ctx, getScoreEventBySession, sessionID)
	var i ScoreEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Game,
		&i.Raw,
		&i.Points,
		&i.AchievedAt,
		&i.ProjectedAt,
	)
	return i, err
}

const listRecentScoreEventsForUser = `-- name: ListRecentScoreEventsForUser :many
SELECT id, user_id, session_id, game, raw, points, achieved_at, projected_at FROM score_events
WHERE user_id = $1
ORDER BY achieved_at DESC
LIMIT $2
`

type ListRecentScoreEventsForUserParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) ListRecentScoreEventsForUser(ctx context.Context, arg ListRecentScoreEventsForUserParams) ([]ScoreEvent, error) {
	rows, err := q.db.Query(ctx, listRecentScoreEventsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScoreEvent{}
	for rows.Next() {
		var i ScoreEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Game,
			&i.Raw,
			&i.Points,
			&i.AchievedAt,
			&i.ProjectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGameSession = `-- name: LockGameSession :one
SELECT id, user_id, game, seed, state, status, moves, started_at, deadline_at, finished_at FROM game_sessions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockGameSession(ctx context.Context, id uuid.UUID) (GameSession, error) {
	row := q.db.QueryRow(ctx, lockGameSession, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Game,
		&i.Seed,
		&i.State,
		&i.Status,
		&i.Moves,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
	)
	return i, err
}

const saveGameSessionState = `-- name: SaveGameSessionState :one
UPDATE game_sessions
SET state = $2,
    moves = moves + 1
WHERE id = $1
RETURNING id, user_id, game, seed, state, status, moves, started_at, deadline_at, finished_at
`

type SaveGameSessionStateParams struct {
	ID    uuid.UUID
	State []byte
}

func (q *Queries) SaveGameSessionState(ctx context.Context, arg SaveGameSessionStateParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, saveGameSessionState, arg.ID, arg.State)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Game,
		&i.Seed,
		&i.State,
		&i.Status,
		&i.Moves,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
	)
	return i, err
}
